---
- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- name: Install gcc 
  yum: name=gcc-c++ state=latest

- name: Install git
  yum: name=git state=latest

- name: Set up iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables
