---
- name: Add user
  user: name={{user_name}} groups=wheel

- name: Allow wheel group to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: "^# %wheel\\s+ALL=\\(ALL\\)\\s+ALL"
    line: "%wheel ALL=(ALL) ALL"
    validate: "visudo -cf %s"
    backup: yes

- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- name: Install gcc 
  yum: name=gcc-c++ state=latest

- name: Install git
  yum: name=git state=latest

- name: Set up iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables
