---
- name: Download WordPress
  get_url: url=http://ja.wordpress.org/wordpress-{{ wp_version }}-ja.tar.gz dest=/srv/wordpress-{{ wp_version }}-ja.tar.gz

- name: Extract archive
  command: chdir=/srv /bin/tar xvf wordpress-{{ wp_version }}-ja.tar.gz creates=/srv/wordpress

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Copy Wordpress to document_root
  command: cp -R /srv/wordpress {{ document_root }}/ creates={{ document_root }}/wordpress

- name: Change ownership of WordPress installation
  file: path={{ document_root }}/wordpress owner=nginx group=nginx state=directory recurse=yes


- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present


